#!/bin/bash
MINIC_LN=$(which minic 2>/dev/null)
if [[ -n $MINIC_LN ]]
then
   MINIC=$(readlink -f $MINIC_LN)
else
   MINIC=$0
fi
ROOT_DIR=$(dirname $MINIC)/..
java -cp ${ROOT_DIR}/lib/*:${ROOT_DIR}/out Main "$@"
